CREATE TABLE IF NOT EXISTS users(
	user_id INT GENERATED BY DEFAULT AS IDENTITY,
    user_login varchar(256) NOT NULL UNIQUE,
	user_password varchar(256) NOT NULL,
	user_email varchar(256) NOT NULL,
	is_admin BIT DEFAULT 0 NOT NULL,
	PRIMARY KEY(user_id),
	CHECK(LENGTH(user_login)>=6),
	CHECK(LENGTH(user_password)>=6)
);

INSERT INTO USERS VALUES (666,'Admin666',
							  'b10249b3b99c35a0fca54c73c2194879343ff6ebd35fe937b20f4e528522bb8c',
                              'alexanidandr@gmail.com', 1);