CREATE TABLE IF NOT EXISTS users(
	user_id INT GENERATED BY DEFAULT AS IDENTITY,
    user_login varchar(256) NOT NULL UNIQUE,
	user_password varchar(256) NOT NULL,
	user_email varchar(256) NOT NULL,
	is_admin BOOLEAN DEFAULT false NOT NULL,
	PRIMARY KEY(user_id),
	CHECK(LENGTH(user_login)>=6),
	CHECK(LENGTH(user_password)>=6)
);

INSERT INTO USERS VALUES (666,'Admin666',
							  'Admin666',
                              'alexanidandr@gmail.com', true);

create or replace function login_user(
    user_login_n users.user_login%type,
    user_password_n users.user_password%type
) returns INT
language plpgsql
as
$body$
declare
    found_id INT;
begin

    SELECT users.user_id
        INTO found_id
            FROM users
                WHERE (users.user_login LIKE user_login_n AND user_password LIKE user_password_n);
    
    IF found_id IS NULL then
    found_id := -1;
    END IF;

    return found_id;
    exception
        when others then
            return -1;
end;
$body$

create or replace function get_user_info(
    u_id int
) RETURNS users
language sql
as
$body$
    select * from users
    where users.user_id = u_id;
$body$